config/routes.rb
Rails4DeviseCancan::Application.routes.draw do
  resources :roles

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    # Define abilities for the passed in user here
    if user.role? :admin
      can :manage, :all
    end
    

    # The first argument to `can` is the action you are giving the user 
    # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
    
    # The second argument is the resource the user can perform the action on. 
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
   
    # The third argument is an optional hash of conditions to further filter the objects.    
      # For example, can :update, Article, :published => true
      # Here the user can only update published articles.  
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :roles_users

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  # checks for the user role
  # input: role symbol
  # ouput: boolean
  def role?(role)
    roles.pluck(:name).include? role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Authorization exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "Access denied."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :is_admin?
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end

    # Only allow admin to access roles.
    def is_admin?
      unless current_user.role?(:admin)
        flash[:alert] = "Access denied."
        redirect_to root_path and return 
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(users_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end


  private
  
    # Only allow a trusted parameter "white list" through.
	  def users_params
	    params.require(:user).permit(:id, :email, :encrypted_password, :created_at, :updated_at, :role_ids)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.email, user}

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= nav_bar responsive: true, inverse: true , fixed: :top, brand: "Rails4-Devise-Cancan-Bootstrap" do
  = menu_group do
    = menu_item "Home", root_path
    = menu_item "Users", users_path
    = menu_item "Roles", roles_path
  = menu_group pull: :right do
    - if user_signed_in?
      %li
        %a 
          %strong Logged in as #{current_user.email}
      = menu_item 'Edit profile', edit_user_registration_path
      = menu_item "Logout", destroy_user_session_path, method: :delete
    - else
      = menu_item "Sign Up", new_user_registration_path
      = menu_item "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Rails4 Devise Cancan Bootstrap'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Rails4 Devise Cancan Bootstrap'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/roles/_form.html.haml
.form-horizontal
  = simple_form_for(@role) do |f|
    = f.error_notification
    .form-group
      .col-sm-offset-1.col-sm-10
        = f.input :name, class: 'form-control'
    .form-group
      .col-sm-offset-1.col-sm-10
        = f.button :submit, class: 'btn btn-primary'

app/views/roles/edit.html.haml
.col-sm-offset-1
	%h1 Editing role

= render 'form'

= link_to 'Show', @role, class: 'col-sm-offset-1'
\|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h3 Roles
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Name
        %th
        %th
        %th
    %tbody
      - @roles.each do |role|
        %tr
          %td= role.name.titleize
          %td= link_to 'Show', role
          %td= link_to 'Edit', edit_role_path(role)
          %td= link_to 'Destroy', role, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

%br

= link_to 'New Role', new_role_path, :class => 'btn btn-primary'

app/views/roles/new.html.haml
.col-sm-offset-1
	%h1 New role

= render 'form'

= link_to 'Back', roles_path, class: 'col-sm-offset-1'

app/views/roles/show.html.haml
%h3 Role Name
%p 
  = @role.name.titleize if @role.name
%br
= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-dialog
      .modal-content
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h3 Change Role
        .modal-body
          = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
        .modal-footer
          = f.submit "Change Role", :class => "btn btn-primary"
          %a.btn.btn-danger{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Email
        %th Registered on
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.email, user
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-primary{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  Email: #{@user.email if @user.email}